name: Deploy Frontend MIRÃ“

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'

    - name: Install OpenConnect
      run: sudo apt-get install -y openconnect

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Connect to VPN
      env:
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_HOST: ${{ secrets.VPN_HOST }}
      run: |
        echo "$VPN_PASSWORD" | sudo openconnect \
          --protocol=gp \
          --user="$VPN_USER" \
          --passwd-on-stdin \
          --servercert pin-sha256:+4XOhCB4GmaXr8/TMWL09EayWRbrz3X8WWAWgu79f9U= \
          "$VPN_HOST" -b

      env:
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_HOST: ${{ secrets.VPN_HOST }}

    - name: Verify VPN connection
      run: ip a

    - name: List network routes
      run: ip route

    - name: Test internal connectivity with SSH
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} 'echo "SSH connection successful"'
        
    - name: Clone repository on remote server
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          cd ~/MIRO/Front_Miro || exit;
          if [ ! -d ".git" ]; then
            git clone https://github.com/BrayanD117/Front_Miro.git
          else
            git pull
          fi'

    - name: Build project on remote server
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          cd ~/MIRO/Front_Miro;
          npm install;
          npm run build'

    - name: Run Semantic Release
      working-directory: ./    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

    - name: Restart PM2
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} 'cd ~/MIRO/Front_Miro && pm2 restart Front_Miro'

    - name: Post Checkout repository
      run: echo "Deployment complete"
