name: Deploy Frontend MIRÃ“ Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'

    - name: Install OpenConnect
      run: sudo apt-get install -y openconnect

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Connect to VPN
      run: |
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect --protocol=gp --user=${{ secrets.VPN_USER }} --passwd-on-stdin ${{ secrets.VPN_HOST }} -b
      env:
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_HOST: ${{ secrets.VPN_HOST }}

    - name: Verify VPN connection
      run: ip a

    - name: List network routes
      run: ip route

    - name: Test internal connectivity with SSH
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} 'echo "SSH connection successful"'
    - name: Update Repository on Remote Server
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          cd ~/MIRO_TEST/Front_Miro_Test;
          echo "ðŸ›‘ Stoping PM2...";
          pm2 stop Front_Dev || true;
          pm2 delete Front_Dev || true;
          echo "ðŸ“¥ Updating repository...";
          git fetch origin develop;
          git reset --hard origin/develop;
          git clean -fd;
          echo "âœ… Repository updted successfully";'
    - name: Build and Restart PM2 for Development
      run: |
        sshpass -p "${{ secrets.INTERNAL_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_RESOURCE_IP }} '
          cd ~/MIRO_TEST/Front_Miro_Test;
          echo "ðŸ“¦ Installing dependencies...";
          npm install;
          echo "ðŸ”¨ Building project...";
          npm run build;
          echo "ðŸš€ Starting PM2...";
          PORT=3001 pm2 start npm --name "Front_Dev" -- start;
          pm2 save;'
    - name: Run Semantic Release
      working-directory: ./    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
    - name: Post Checkout repository
      run: echo "Development deployment complete"